language: objective-c
osx_image: xcode8
script:
    - xcodebuild clean build -workspace NSManchester.xcworkspace -scheme NSManchester -destination "platform=iOS Simulator,name=iPhone 6S" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
